version: "3.8"

name: puzzles

services:
  mongo:
    image: mongo:7.0.8
    container_name: mongo
    volumes:
      - /dev/volumes/puzzles:/data/db
    networks:
      - puzzlenet
  catalog:
    build: ./services/catalog
    container_name: catalog
    environment:
      - ENV=prod
    ports:
      - "8080:8080"
    image: puzzles-catalog
    depends_on:
      - mongo
    networks:
      - puzzlenet
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - puzzlenet


networks:
  puzzlenet:
    driver: bridge
