version: "3.8"

name: puzzles

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - puzzlenet
  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - puzzlenet
  mongo:
    image: mongo:7.0.8
    container_name: mongo
    volumes:
      - /dev/volumes/puzzles/mongo:/data/db
    networks:
      - puzzlenet
  catalog:
    build: ./services/catalog
    container_name: catalog
    depends_on:
      - mongo
    environment:
      - ENV=prod
    restart: always
    networks:
      - puzzlenet
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - puzzlenet
  basket:
    build: ./services/basket
    container_name: basket
    depends_on:
      - redis
    environment:
      - ENV=prod
    restart: always
    networks:
      - puzzlenet
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=puzzles
      - POSTGRES_PASSWORD=puzzles
      - POSTGRES_DB=puzzles
    networks: 
      - puzzlenet
  order:
    build: ./services/order
    container_name: order
    depends_on:
      - postgres
    environment:
      - ENV=prod
    restart: always
    networks:
      - puzzlenet

networks:
  puzzlenet:
    driver: bridge
