version: "3.8"

name: puzzles

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - puzzlenet
    volumes:
      - ./consul/consul.json:/consul/config/consul.json
  traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - puzzlenet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
  mongo:
    image: mongo:7.0.8
    container_name: mongo
    volumes:
      - /dev/volumes/puzzles/mongo:/data/db
    networks:
      - puzzlenet
  catalog:
    build: ./services/catalog
    container_name: catalog
    environment:
      - ENV=prod
    image: puzzles-catalog
    depends_on:
      - mongo
    networks:
      - puzzlenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalog.rule=PathPrefix(`/catalog`)"
      - "traefik.http.routers.catalog.service=catalog"
      - "traefik.http.services.catalog.loadbalancer.server.port=8080"
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - puzzlenet
  basket:
    build: ./services/basket
    container_name: basket
    environment:
      - ENV=prod
    ports:
      - "8081:8081"
    image: puzzles-basket
    depends_on:
      - redis
    networks:
      - puzzlenet
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=puzzles
      - POSTGRES_PASSWORD=puzzles
      - POSTGRES_DB=puzzles
    networks: 
      - puzzlenet
  orders:
    build: ./services/orders
    container_name: orders
    environment:
      - ENV=prod
    ports:
      - "8082:8082"
    image: puzzles-orders
    depends_on:
      - postgres
    networks:
      - puzzlenet



networks:
  puzzlenet:
    driver: bridge
