port = 8080

[postgres]
host = "postgres"
port = 5432
user = "puzzles"
password = "puzzles"
dbname = "puzzles"
timeout = "15s"

[service]
name = "orders"
address = "orders"
path = "/order"

[consul]
address = "consul:8500"
