api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  consulCatalog:
    endpoint:
      address: "consul:8500"
    prefix: "traefik"
    exposedByDefault: false
