port = 8080

[postgres]
host = "postgres"
port = 5432
user = "puzzles"
password = "puzzles"
dbname = "puzzles"
timeout = "15s"

[service]
name = "order"
address = "order"
path = "/order"

[consul]
address = "consul:8500"

[rabbitmq]
user = "guest"
pass = "guest"
host = "rabbitmq"
port = 5672
queue = "order_queue"
